// Code generated by gola 0.1.1; DO NOT EDIT.

package profile

import (
	"context"
	"database/sql"
	"reflect"
	"strings"

	"github.com/olachat/gola/v2/coredb"
)

// FetchByPK returns a row from `profile` table with given primary key value
func FetchByPKCtx(ctx context.Context, val int) (*Profile, error) {
	return coredb.FetchByPKCtx[Profile](ctx, DBName, TableName, []string{"user_id"}, val)
}

// FetchFieldsByPK returns a row with selected fields from profile table with given primary key value
func FetchFieldsByPKCtx[T any](ctx context.Context, val int) (*T, error) {
	return coredb.FetchByPKCtx[T](ctx, DBName, TableName, []string{"user_id"}, val)
}

// FetchByPKs returns rows with from `profile` table with given primary key values
func FetchByPKsCtx(ctx context.Context, vals ...int) ([]*Profile, error) {
	pks := coredb.GetAnySlice(vals)
	return coredb.FetchByPKsCtx[Profile](ctx, DBName, TableName, "user_id", pks)
}

// FetchFieldsByPKs returns rows with selected fields from `profile` table with given primary key values
func FetchFieldsByPKsCtx[T any](ctx context.Context, vals ...int) ([]*T, error) {
	pks := coredb.GetAnySlice(vals)
	return coredb.FetchByPKsCtx[T](ctx, DBName, TableName, "user_id", pks)
}

// FindOne returns a row from `profile` table with arbitary where query
// whereSQL must start with "where ..."
func FindOneCtx(ctx context.Context, whereSQL string, params ...any) (*Profile, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindOneCtx[Profile](ctx, DBName, TableName, w)
}

// FindOneFields returns a row with selected fields from `profile` table with arbitary where query
// whereSQL must start with "where ..."
func FindOneFieldsCtx[T any](ctx context.Context, whereSQL string, params ...any) (*T, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindOneCtx[T](ctx, DBName, TableName, w)
}

// Find returns rows from `profile` table with arbitary where query
// whereSQL must start with "where ..."
func FindCtx(ctx context.Context, whereSQL string, params ...any) ([]*Profile, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindCtx[Profile](ctx, DBName, TableName, w)
}

// FindFields returns rows with selected fields from `profile` table with arbitary where query
// whereSQL must start with "where ..."
func FindFieldsCtx[T any](ctx context.Context, whereSQL string, params ...any) ([]*T, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindCtx[T](ctx, DBName, TableName, w)
}

// Count returns select count(*) with arbitary where query
// whereSQL must start with "where ..."
func CountCtx(ctx context.Context, whereSQL string, params ...any) (int, error) {
	return coredb.QueryIntCtx(ctx, DBName, "SELECT COUNT(*) FROM `profile` "+whereSQL, params...)
}

// FetchByPK returns a row from `profile` table with given primary key value
func FetchByPKFromMasterCtx(ctx context.Context, val int) (*Profile, error) {
	return coredb.FetchByPKFromMasterCtx[Profile](ctx, DBName, TableName, []string{"user_id"}, val)
}

// FetchFieldsByPK returns a row with selected fields from profile table with given primary key value
func FetchFieldsByPKFromMasterCtx[T any](ctx context.Context, val int) (*T, error) {
	return coredb.FetchByPKFromMasterCtx[T](ctx, DBName, TableName, []string{"user_id"}, val)
}

// FetchByPKs returns rows with from `profile` table with given primary key values
func FetchByPKsFromMasterCtx(ctx context.Context, vals ...int) ([]*Profile, error) {
	pks := coredb.GetAnySlice(vals)
	return coredb.FetchByPKsFromMasterCtx[Profile](ctx, DBName, TableName, "user_id", pks)
}

// FetchFieldsByPKs returns rows with selected fields from `profile` table with given primary key values
func FetchFieldsByPKsFromMasterCtx[T any](ctx context.Context, vals ...int) ([]*T, error) {
	pks := coredb.GetAnySlice(vals)
	return coredb.FetchByPKsFromMasterCtx[T](ctx, DBName, TableName, "user_id", pks)
}

// FindOne returns a row from `profile` table with arbitary where query
// whereSQL must start with "where ..."
func FindOneFromMasterCtx(ctx context.Context, whereSQL string, params ...any) (*Profile, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindOneFromMasterCtx[Profile](ctx, DBName, TableName, w)
}

// FindOneFields returns a row with selected fields from `profile` table with arbitary where query
// whereSQL must start with "where ..."
func FindOneFieldsFromMasterCtx[T any](ctx context.Context, whereSQL string, params ...any) (*T, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindOneFromMasterCtx[T](ctx, DBName, TableName, w)
}

// Find returns rows from `profile` table with arbitary where query
// whereSQL must start with "where ..."
func FindFromMasterCtx(ctx context.Context, whereSQL string, params ...any) ([]*Profile, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindFromMasterCtx[Profile](ctx, DBName, TableName, w)
}

// FindFields returns rows with selected fields from `profile` table with arbitary where query
// whereSQL must start with "where ..."
func FindFieldsFromMasterCtx[T any](ctx context.Context, whereSQL string, params ...any) ([]*T, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindFromMasterCtx[T](ctx, DBName, TableName, w)
}

// Count returns select count(*) with arbitary where query
// whereSQL must start with "where ..."
func CountFromMasterCtx(ctx context.Context, whereSQL string, params ...any) (int, error) {
	return coredb.QueryIntFromMasterCtx(ctx, DBName, "SELECT COUNT(*) FROM `profile` "+whereSQL, params...)
}

// Insert Profile struct to `profile` table
func (c *Profile) InsertCtx(ctx context.Context) error {
	var result sql.Result
	var err error
	result, err = coredb.ExecCtx(ctx, DBName, insertWithoutPK, c.getUserIdForDB(), c.getLevelForDB(), c.getNickNameForDB())
	if err != nil {
		return err
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return err
	}
	if affectedRows == 0 {
		return coredb.ErrAvoidInsert
	}

	c.resetUpdated()
	return nil
}

// Update Profile struct in `profile` table
func (obj *Profile) UpdateCtx(ctx context.Context) (bool, error) {
	var updatedFields []string
	var params []any
	if obj.Level.IsUpdated() {
		updatedFields = append(updatedFields, "`level` = ?")
		params = append(params, obj.getLevelForDB())
	}
	if obj.NickName.IsUpdated() {
		updatedFields = append(updatedFields, "`nick_name` = ?")
		params = append(params, obj.getNickNameForDB())
	}

	if len(updatedFields) == 0 {
		return false, nil
	}

	sql := "UPDATE `profile` SET "
	sql = sql + strings.Join(updatedFields, ",") + " WHERE `user_id` = ?"
	params = append(params, obj.GetUserId())

	result, err := coredb.ExecCtx(ctx, DBName, sql, params...)
	if err != nil {
		return false, err
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return false, err
	}
	if affectedRows == 0 {
		return false, coredb.ErrAvoidUpdate
	}

	obj.resetUpdated()
	return true, nil
}

// Update Profile struct with given fields in `profile` table
func UpdateCtx(ctx context.Context, obj withPK) (bool, error) {
	var updatedFields []string
	var params []any
	var resetFuncs []func()

	val := reflect.ValueOf(obj).Elem()
	updatedFields = make([]string, 0, val.NumField())
	params = make([]any, 0, val.NumField())

	for i := 0; i < val.NumField(); i++ {
		col := val.Field(i).Addr().Interface()

		switch c := col.(type) {
		case *Level:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`level` = ?")
				params = append(params, c.getLevelForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *NickName:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`nick_name` = ?")
				params = append(params, c.getNickNameForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		}
	}

	if len(updatedFields) == 0 {
		return false, nil
	}

	sql := "UPDATE `profile` SET "
	sql = sql + strings.Join(updatedFields, ",") + " WHERE `user_id` = ?"
	params = append(params, obj.GetUserId())

	result, err := coredb.ExecCtx(ctx, DBName, sql, params...)
	if err != nil {
		return false, err
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return false, err
	}
	if affectedRows == 0 {
		return false, coredb.ErrAvoidUpdate
	}

	for _, f := range resetFuncs {
		f()
	}
	return true, nil
}

// DeleteByPK delete a row from profile table with given primary key value
func DeleteByPKCtx(ctx context.Context, val int) error {
	_, err := coredb.ExecCtx(ctx, DBName, deleteSql, val)
	return err
}
