// Code generated by gola 0.0.4; DO NOT EDIT.

package profile

import (
	"reflect"
	"strings"

	"github.com/olachat/gola/coredb"
)

var DBName string = "testdata"

func Setup(dbname string) {
	DBName = dbname
}

// Profile represents profile table
type Profile struct {
	//  int
	UserId
	//  tinyint(4)
	Level
	// Nick Name varchar
	NickName
}

type ProfileTable struct{}

func (*ProfileTable) GetTableName() string {
	return "profile"
}

var table *ProfileTable

type withPK interface {
	GetUserId() int
}

// FetchProfileByPKs returns a row from profile table with given primary key value
func FetchProfileByPK(val int) *Profile {
	return coredb.FetchByPK[Profile](DBName, []string{"user_id"}, val)
}

// FetchByPKs returns a row with selected fields from profile table with given primary key value
func FetchByPK[T any](val int) *T {
	return coredb.FetchByPK[T](DBName, []string{"user_id"}, val)
}

// FetchProfileByPKs returns rows with from profile table with given primary key values
func FetchProfileByPKs(vals ...int) []*Profile {
	pks := coredb.GetAnySlice(vals)
	return coredb.FetchByPKs[Profile](pks, "user_id", DBName)
}

// FetchByPKs returns rows with selected fields from profile table with given primary key values
func FetchByPKs[T any](vals ...int) []*T {
	pks := coredb.GetAnySlice(vals)
	return coredb.FetchByPKs[T](pks, "user_id", DBName)
}

// FindOneProfile returns a row from profile table with arbitary where query
// whereSQL must start with "where ..."
func FindOneProfile(whereSQL string, params ...any) *Profile {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindOne[Profile](w, DBName)
}

// Count returns select count(*) with arbitary where query
// whereSQL must start with "where ..."
func Count(whereSQL string, params ...any) (int, error) {
	return coredb.QueryInt("SELECT COUNT(*) FROM `profile` "+whereSQL, DBName, params...)
}

// FindOne returns a row with selected fields from profile table with arbitary where query
// whereSQL must start with "where ..."
func FindOne[T any](whereSQL string, params ...any) *T {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindOne[T](w, DBName)
}

// FindProfile returns rows from profile table with arbitary where query
// whereSQL must start with "where ..."
func FindProfile(whereSQL string, params ...any) ([]*Profile, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.Find[Profile](w, DBName)
}

// Find returns rows with selected fields from profile table with arbitary where query
// whereSQL must start with "where ..."
func Find[T any](whereSQL string, params ...any) ([]*T, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.Find[T](w, DBName)
}

// Column types

// UserId field
//
type UserId struct {
	val int
}

func (c *UserId) GetUserId() int {
	return c.val
}

func (c *UserId) GetColumnName() string {
	return "user_id"
}

func (c *UserId) IsPrimaryKey() bool {
	return true
}

func (c *UserId) GetValPointer() any {
	return &c.val
}

func (c *UserId) GetTableType() coredb.TableType {
	return table
}

// Level field
//
type Level struct {
	_updated bool
	val      int8
}

func (c *Level) GetLevel() int8 {
	return c.val
}

func (c *Level) SetLevel(val int8) bool {
	if c.val == val {
		return false
	}
	c._updated = true
	c.val = val
	return true
}

func (c *Level) IsUpdated() bool {
	return c._updated
}

func (c *Level) resetUpdated() {
	c._updated = false
}

func (c *Level) GetColumnName() string {
	return "level"
}

func (c *Level) IsPrimaryKey() bool {
	return false
}

func (c *Level) GetValPointer() any {
	return &c.val
}

func (c *Level) GetTableType() coredb.TableType {
	return table
}

// NickName field
// Nick Name
type NickName struct {
	_updated bool
	val      string
}

func (c *NickName) GetNickName() string {
	return c.val
}

func (c *NickName) SetNickName(val string) bool {
	if c.val == val {
		return false
	}
	c._updated = true
	c.val = val
	return true
}

func (c *NickName) IsUpdated() bool {
	return c._updated
}

func (c *NickName) resetUpdated() {
	c._updated = false
}

func (c *NickName) GetColumnName() string {
	return "nick_name"
}

func (c *NickName) IsPrimaryKey() bool {
	return false
}

func (c *NickName) GetValPointer() any {
	return &c.val
}

func (c *NickName) GetTableType() coredb.TableType {
	return table
}

// NewProfileWithPK takes "user_id"
// and returns new *Profile with given PK
func NewProfileWithPK(val int) *Profile {
	c := &Profile{
		UserId{},
		Level{val: int8(1)},
		NickName{},
	}
	c.UserId.val = val
	return c
}

func (c *Profile) Insert() error {
	sql := "INSERT IGNORE INTO `profile` (`user_id`, `level`, `nick_name`) values (?, ?, ?)"

	result, err := coredb.Exec(sql, DBName, c.GetUserId(), c.GetLevel(), c.GetNickName())

	if err != nil {
		return err
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return err
	}
	if affectedRows == 0 {
		return coredb.ErrAvoidInsert
	}

	c.resetUpdated()
	return nil
}

func (c *Profile) resetUpdated() {
	c.Level.resetUpdated()
	c.NickName.resetUpdated()
}

func (obj *Profile) Update() (bool, error) {
	var updatedFields []string
	var params []any
	if obj.Level.IsUpdated() {
		updatedFields = append(updatedFields, "`level` = ?")
		params = append(params, obj.GetLevel())
	}
	if obj.NickName.IsUpdated() {
		updatedFields = append(updatedFields, "`nick_name` = ?")
		params = append(params, obj.GetNickName())
	}

	if len(updatedFields) == 0 {
		return false, nil
	}

	sql := "UPDATE `profile` SET "
	sql = sql + strings.Join(updatedFields, ",") + " WHERE `user_id` = ?"
	params = append(params, obj.GetUserId())

	result, err := coredb.Exec(sql, DBName, params...)
	if err != nil {
		return false, err
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return false, err
	}
	if affectedRows == 0 {
		return false, coredb.ErrAvoidUpdate
	}

	obj.resetUpdated()
	return true, nil
}

func Update(obj withPK) (bool, error) {
	var updatedFields []string
	var params []any
	var resetFuncs []func()

	val := reflect.ValueOf(obj).Elem()
	updatedFields = make([]string, 0, val.NumField())
	params = make([]any, 0, val.NumField())

	for i := 0; i < val.NumField(); i++ {
		col := val.Field(i).Addr().Interface()

		switch c := col.(type) {
		case *Level:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`level` = ?")
				params = append(params, c.GetLevel())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *NickName:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`nick_name` = ?")
				params = append(params, c.GetNickName())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		}
	}

	if len(updatedFields) == 0 {
		return false, nil
	}

	sql := "UPDATE `profile` SET "
	sql = sql + strings.Join(updatedFields, ",") + " WHERE `user_id` = ?"
	params = append(params, obj.GetUserId())

	result, err := coredb.Exec(sql, DBName, params...)
	if err != nil {
		return false, err
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return false, err
	}
	if affectedRows == 0 {
		return false, coredb.ErrAvoidUpdate
	}

	for _, f := range resetFuncs {
		f()
	}
	return true, nil
}

func (obj *Profile) Delete() error {
	sql := "DELETE FROM `profile` WHERE `user_id` = ?"

	_, err := coredb.Exec(sql, DBName, obj.GetUserId())
	return err
}

func Delete(obj withPK) error {
	sql := "DELETE FROM `profile` WHERE `user_id` = ?"

	_, err := coredb.Exec(sql, DBName, obj.GetUserId())
	return err
}
