// Code generated by gola 0.0.3; DO NOT EDIT.

package account

import (
	"database/sql"
	"reflect"
	"strings"

	"github.com/olachat/gola/coredb"
)

var _db *sql.DB

func Setup(db *sql.DB) {
	_db = db
}

// Account represents account table
type Account struct {
	//  int
	UserId
	// user account type enum('free','vip')
	Type
	// Account money int
	Money
}

type AccountTable struct{}

func (*AccountTable) GetTableName() string {
	return "account"
}

var table *AccountTable

type PK struct {
	UserId int
	Type   AccountType
}

type withPK interface {
	GetUserId() int
	GetType() AccountType
}

// FetchAccountByPKs returns a row from account table with given primary key value
func FetchAccountByPK(val PK) *Account {
	return coredb.FetchByPK[Account](_db, []string{"user_id", "type"}, val.UserId, val.Type)
}

// FetchByPKs returns a row with selected fields from account table with given primary key value
func FetchByPK[T any](val PK) *T {
	return coredb.FetchByPK[T](_db, []string{"user_id", "type"}, val.UserId, val.Type)
}

// FindOneAccount returns a row from account table with arbitary where query
// whereSQL must start with "where ..."
func FindOneAccount(whereSQL string, params ...any) *Account {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindOne[Account](w, _db)
}

// Count returns select count(*) with arbitary where query
// whereSQL must start with "where ..."
func Count(whereSQL string, params ...any) (int, error) {
	return coredb.QueryInt("SELECT COUNT(*) FROM `account` "+whereSQL, _db, params...)
}

// FindOne returns a row with selected fields from account table with arbitary where query
// whereSQL must start with "where ..."
func FindOne[T any](whereSQL string, params ...any) *T {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindOne[T](w, _db)
}

// FindAccount returns rows from account table with arbitary where query
// whereSQL must start with "where ..."
func FindAccount(whereSQL string, params ...any) ([]*Account, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.Find[Account](w, _db)
}

// Find returns rows with selected fields from account table with arbitary where query
// whereSQL must start with "where ..."
func Find[T any](whereSQL string, params ...any) ([]*T, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.Find[T](w, _db)
}

// Column types
type AccountType string

const (
	AccountTypeFree AccountType = "free"
	AccountTypeVip  AccountType = "vip"
)

// UserId field
//
type UserId struct {
	val int
}

func (c *UserId) GetUserId() int {
	return c.val
}

func (c *UserId) GetColumnName() string {
	return "user_id"
}

func (c *UserId) IsPrimaryKey() bool {
	return true
}

func (c *UserId) GetValPointer() any {
	return &c.val
}

func (c *UserId) GetTableType() coredb.TableType {
	return table
}

// Type field
// user account type
type Type struct {
	val AccountType
}

func (c *Type) GetType() AccountType {
	return c.val
}

func (c *Type) GetColumnName() string {
	return "type"
}

func (c *Type) IsPrimaryKey() bool {
	return true
}

func (c *Type) GetValPointer() any {
	return &c.val
}

func (c *Type) GetTableType() coredb.TableType {
	return table
}

// Money field
// Account money
type Money struct {
	_updated bool
	val      int
}

func (c *Money) GetMoney() int {
	return c.val
}

func (c *Money) SetMoney(val int) bool {
	if c.val == val {
		return false
	}
	c._updated = true
	c.val = val
	return true
}

func (c *Money) IsUpdated() bool {
	return c._updated
}

func (c *Money) resetUpdated() {
	c._updated = false
}

func (c *Money) GetColumnName() string {
	return "money"
}

func (c *Money) IsPrimaryKey() bool {
	return false
}

func (c *Money) GetValPointer() any {
	return &c.val
}

func (c *Money) GetTableType() coredb.TableType {
	return table
}

func NewAccountWithPK(val PK) *Account {
	c := &Account{
		UserId{},
		Type{val: "free"},
		Money{val: int(0)},
	}
	c.UserId.val = val.UserId
	c.Type.val = val.Type
	return c
}

func (c *Account) Insert() error {
	sql := "INSERT IGNORE INTO `account` (`user_id`, `type`, `money`) values (?, ?, ?)"

	result, err := coredb.Exec(sql, _db, c.GetUserId(), c.GetType(), c.GetMoney())

	if err != nil {
		return err
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return err
	}
	if affectedRows == 0 {
		return coredb.ErrAvoidInsert
	}

	c.resetUpdated()
	return nil
}

func (c *Account) resetUpdated() {
	c.Money.resetUpdated()
}

func (obj *Account) Update() (bool, error) {
	var updatedFields []string
	var params []any
	if obj.Money.IsUpdated() {
		updatedFields = append(updatedFields, "`money` = ?")
		params = append(params, obj.GetMoney())
	}

	if len(updatedFields) == 0 {
		return false, nil
	}

	sql := "UPDATE `account` SET "
	sql = sql + strings.Join(updatedFields, ",") + " WHERE `user_id` = ? and `type` = ?"
	params = append(params, obj.GetUserId(), obj.GetType())

	result, err := coredb.Exec(sql, _db, params...)
	if err != nil {
		return false, err
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return false, err
	}
	if affectedRows == 0 {
		return false, coredb.ErrAvoidUpdate
	}

	obj.resetUpdated()
	return true, nil
}

func Update(obj withPK) (bool, error) {
	var updatedFields []string
	var params []any
	var resetFuncs []func()

	val := reflect.ValueOf(obj).Elem()
	updatedFields = make([]string, 0, val.NumField())
	params = make([]any, 0, val.NumField())

	for i := 0; i < val.NumField(); i++ {
		col := val.Field(i).Addr().Interface()

		switch c := col.(type) {
		case *Money:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`money` = ?")
				params = append(params, c.GetMoney())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		}
	}

	if len(updatedFields) == 0 {
		return false, nil
	}

	sql := "UPDATE `account` SET "
	sql = sql + strings.Join(updatedFields, ",") + " WHERE `user_id` = ? and `type` = ?"
	params = append(params, obj.GetUserId(), obj.GetType())

	result, err := coredb.Exec(sql, _db, params...)
	if err != nil {
		return false, err
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return false, err
	}
	if affectedRows == 0 {
		return false, coredb.ErrAvoidUpdate
	}

	for _, f := range resetFuncs {
		f()
	}
	return true, nil
}

func (obj *Account) Delete() error {
	sql := "DELETE FROM `account` WHERE `user_id` = ? and `type` = ?"

	_, err := coredb.Exec(sql, _db, obj.GetUserId(), obj.GetType())
	return err
}

func Delete(obj withPK) error {
	sql := "DELETE FROM `account` WHERE `user_id` = ? and `type` = ?"

	_, err := coredb.Exec(sql, _db, obj.GetUserId(), obj.GetType())
	return err
}
