// Code generated by gola 0.0.3; DO NOT EDIT.

package account

import (
	"fmt"
	"strings"

	"github.com/olachat/gola/coredb"
)

type orderBy int

type idxQuery[T any] struct {
	whereSql    string
	limitSql    string
	orders      []string
	whereParams []any
}

// order by enum & interface
const (
	UserIdAsc orderBy = iota
	UserIdDesc
	TypeAsc
	TypeDesc
	CountryCodeAsc
	CountryCodeDesc
	MoneyAsc
	MoneyDesc
)

func (q *idxQuery[T]) OrderBy(args ...orderBy) coredb.ReadQuery[T] {
	q.orders = make([]string, len(args))
	for i, arg := range args {
		switch arg {
		case UserIdAsc:
			q.orders[i] = "`user_id` asc"
		case UserIdDesc:
			q.orders[i] = "`user_id` desc"
		case TypeAsc:
			q.orders[i] = "`type` asc"
		case TypeDesc:
			q.orders[i] = "`type` desc"
		case CountryCodeAsc:
			q.orders[i] = "`country_code` asc"
		case CountryCodeDesc:
			q.orders[i] = "`country_code` desc"
		case MoneyAsc:
			q.orders[i] = "`money` asc"
		case MoneyDesc:
			q.orders[i] = "`money` desc"
		}
	}
	return q
}

func (q *idxQuery[T]) All() []*T {
	result, _ := coredb.Find[T](q, _db)
	return result
}

func (q *idxQuery[T]) Limit(offset, count int) []*T {
	q.limitSql = fmt.Sprintf(" limit %d, %d", offset, count)
	result, _ := coredb.Find[T](q, _db)
	return result
}

type order[T any] interface {
	OrderBy(args ...orderBy) coredb.ReadQuery[T]
}

type orderReadQuery[T any] interface {
	order[T]
	coredb.ReadQuery[T]
}

type iQuery[T any] interface {
	WhereUserIdEQ(val int) iQuery1[T]
	WhereUserIdIN(vals ...int) iQuery1[T]
	orderReadQuery[T]
}
type iQuery1[T any] interface {
	AndCountryCodeEQ(val int) orderReadQuery[T]
	AndCountryCodeIN(vals ...int) orderReadQuery[T]
	orderReadQuery[T]
}

type idxQuery1[T any] struct {
	*idxQuery[T]
}

func (q *idxQuery1[T]) AndCountryCodeEQ(val int) orderReadQuery[T] {
	q.whereSql = " and `user_id` = ?"
	q.whereParams = append(q.whereParams, val)
	return q.idxQuery
}

func (q *idxQuery1[T]) AndCountryCodeIN(vals ...int) orderReadQuery[T] {
	q.whereSql += " and `user_id` in (" + coredb.GetParamPlaceHolder(len(vals)) + ")"
	for _, val := range vals {
		q.whereParams = append(q.whereParams, val)
	}
	return q.idxQuery
}

// Find methods
func SelectAccount() iQuery[Account] {
	return new(idxQuery[Account])
}

func Select[T any]() iQuery[T] {
	return new(idxQuery[T])
}

func (q *idxQuery[T]) WhereUserIdEQ(val int) iQuery1[T] {
	q.whereSql += " where `user_id` = ?"
	q.whereParams = append(q.whereParams, val)
	return &idxQuery1[T]{q}
}

func (q *idxQuery[T]) WhereUserIdIN(vals ...int) iQuery1[T] {
	q.whereSql = " where `user_id` in (" + coredb.GetParamPlaceHolder(len(vals)) + ")"
	for _, val := range vals {
		q.whereParams = append(q.whereParams, val)
	}
	return &idxQuery1[T]{q}
}

func (q *idxQuery[T]) GetWhere() (whereSql string, params []any) {
	var orderSql string
	if len(q.orders) > 0 {
		orderSql = " order by " + strings.Join(q.orders, ",")
	}
	return q.whereSql + orderSql + q.limitSql, q.whereParams
}
