// Code generated by gola 0.1.1; DO NOT EDIT.

package users

import (
	"context"
	"database/sql"
	"reflect"
	"strings"

	"github.com/olachat/gola/v2/coredb"
	"github.com/olachat/gola/v2/coredb/txengine"
)

// InsertTx inserts User struct to `users` table with transaction
func (c *User) InsertTx(ctx context.Context, tx *sql.Tx) error {
	var result sql.Result
	var err error
	if c.Id.isAssigned {
		result, err = txengine.WithTx(tx).Exec(ctx, insertWithPK, c.getIdForDB(), c.getNameForDB(), c.getEmailForDB(), c.getCreatedAtForDB(), c.getUpdatedAtForDB(), c.getFloatTypeForDB(), c.getDoubleTypeForDB(), c.getHobbyForDB(), c.getHobbyNoDefaultForDB(), c.getSportsForDB(), c.getSports2ForDB(), c.getSportsNoDefaultForDB())
		if err != nil {
			return err
		}
	} else {
		result, err = txengine.WithTx(tx).Exec(ctx, insertWithoutPK, c.getNameForDB(), c.getEmailForDB(), c.getCreatedAtForDB(), c.getUpdatedAtForDB(), c.getFloatTypeForDB(), c.getDoubleTypeForDB(), c.getHobbyForDB(), c.getHobbyNoDefaultForDB(), c.getSportsForDB(), c.getSports2ForDB(), c.getSportsNoDefaultForDB())
		if err != nil {
			return err
		}

		id, err := result.LastInsertId()
		if err != nil {
			return err
		}
		c.Id.val = int(id)
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return err
	}
	if affectedRows == 0 {
		return coredb.ErrAvoidInsert
	}

	c.resetUpdated()
	return nil
}

// UpdateTx updates User struct in `users` table with transaction
func (obj *User) UpdateTx(ctx context.Context, tx *sql.Tx) (bool, error) {
	var updatedFields []string
	var params []any
	if obj.Name.IsUpdated() {
		updatedFields = append(updatedFields, "`name` = ?")
		params = append(params, obj.getNameForDB())
	}
	if obj.Email.IsUpdated() {
		updatedFields = append(updatedFields, "`email` = ?")
		params = append(params, obj.getEmailForDB())
	}
	if obj.CreatedAt.IsUpdated() {
		updatedFields = append(updatedFields, "`created_at` = ?")
		params = append(params, obj.getCreatedAtForDB())
	}
	if obj.UpdatedAt.IsUpdated() {
		updatedFields = append(updatedFields, "`updated_at` = ?")
		params = append(params, obj.getUpdatedAtForDB())
	}
	if obj.FloatType.IsUpdated() {
		updatedFields = append(updatedFields, "`float_type` = ?")
		params = append(params, obj.getFloatTypeForDB())
	}
	if obj.DoubleType.IsUpdated() {
		updatedFields = append(updatedFields, "`double_type` = ?")
		params = append(params, obj.getDoubleTypeForDB())
	}
	if obj.Hobby.IsUpdated() {
		updatedFields = append(updatedFields, "`hobby` = ?")
		params = append(params, obj.getHobbyForDB())
	}
	if obj.HobbyNoDefault.IsUpdated() {
		updatedFields = append(updatedFields, "`hobby_no_default` = ?")
		params = append(params, obj.getHobbyNoDefaultForDB())
	}
	if obj.Sports.IsUpdated() {
		updatedFields = append(updatedFields, "`sports` = ?")
		params = append(params, obj.getSportsForDB())
	}
	if obj.Sports2.IsUpdated() {
		updatedFields = append(updatedFields, "`sports2` = ?")
		params = append(params, obj.getSports2ForDB())
	}
	if obj.SportsNoDefault.IsUpdated() {
		updatedFields = append(updatedFields, "`sports_no_default` = ?")
		params = append(params, obj.getSportsNoDefaultForDB())
	}

	if len(updatedFields) == 0 {
		return false, nil
	}

	sql := "UPDATE `users` SET "
	sql = sql + strings.Join(updatedFields, ",") + " WHERE `id` = ?"
	params = append(params, obj.GetId())

	result, err := txengine.WithTx(tx).Exec(ctx, sql, params...)
	if err != nil {
		return false, err
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return false, err
	}
	if affectedRows == 0 {
		return false, coredb.ErrAvoidUpdate
	}

	obj.resetUpdated()
	return true, nil
}

// UpdateTx updates User struct with given fields in `users` table with transaction
func UpdateTx(ctx context.Context, tx *sql.Tx, obj withPK) (bool, error) {
	var updatedFields []string
	var params []any
	var resetFuncs []func()

	val := reflect.ValueOf(obj).Elem()
	updatedFields = make([]string, 0, val.NumField())
	params = make([]any, 0, val.NumField())

	for i := 0; i < val.NumField(); i++ {
		col := val.Field(i).Addr().Interface()

		switch c := col.(type) {
		case *Name:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`name` = ?")
				params = append(params, c.getNameForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *Email:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`email` = ?")
				params = append(params, c.getEmailForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *CreatedAt:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`created_at` = ?")
				params = append(params, c.getCreatedAtForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *UpdatedAt:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`updated_at` = ?")
				params = append(params, c.getUpdatedAtForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *FloatType:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`float_type` = ?")
				params = append(params, c.getFloatTypeForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *DoubleType:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`double_type` = ?")
				params = append(params, c.getDoubleTypeForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *Hobby:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`hobby` = ?")
				params = append(params, c.getHobbyForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *HobbyNoDefault:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`hobby_no_default` = ?")
				params = append(params, c.getHobbyNoDefaultForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *Sports:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`sports` = ?")
				params = append(params, c.getSportsForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *Sports2:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`sports2` = ?")
				params = append(params, c.getSports2ForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *SportsNoDefault:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`sports_no_default` = ?")
				params = append(params, c.getSportsNoDefaultForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		}
	}

	if len(updatedFields) == 0 {
		return false, nil
	}

	sql := "UPDATE `users` SET "
	sql = sql + strings.Join(updatedFields, ",") + " WHERE `id` = ?"
	params = append(params, obj.GetId())

	result, err := txengine.WithTx(tx).Exec(ctx, sql, params...)
	if err != nil {
		return false, err
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return false, err
	}
	if affectedRows == 0 {
		return false, coredb.ErrAvoidUpdate
	}

	for _, f := range resetFuncs {
		f()
	}
	return true, nil
}
