// Code generated by gola 0.1.1; DO NOT EDIT.

package wallet

import (
	"context"
	"database/sql"
	"reflect"
	"strings"

	"github.com/olachat/gola/v2/coredb"
)

// FetchByPK returns a row from `wallet` table with given primary key value
func FetchByPKCtx(ctx context.Context, val PK) (*Wallet, error) {
	return coredb.FetchByPKCtx[Wallet](ctx, DBName, TableName, []string{"user_id", "wallet_type"}, val.UserId, val.WalletType)
}

// FetchFieldsByPK returns a row with selected fields from wallet table with given primary key value
func FetchFieldsByPKCtx[T any](ctx context.Context, val PK) (*T, error) {
	return coredb.FetchByPKCtx[T](ctx, DBName, TableName, []string{"user_id", "wallet_type"}, val.UserId, val.WalletType)
}

// FindOne returns a row from `wallet` table with arbitary where query
// whereSQL must start with "where ..."
func FindOneCtx(ctx context.Context, whereSQL string, params ...any) (*Wallet, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindOneCtx[Wallet](ctx, DBName, TableName, w)
}

// FindOneFields returns a row with selected fields from `wallet` table with arbitary where query
// whereSQL must start with "where ..."
func FindOneFieldsCtx[T any](ctx context.Context, whereSQL string, params ...any) (*T, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindOneCtx[T](ctx, DBName, TableName, w)
}

// Find returns rows from `wallet` table with arbitary where query
// whereSQL must start with "where ..."
func FindCtx(ctx context.Context, whereSQL string, params ...any) ([]*Wallet, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindCtx[Wallet](ctx, DBName, TableName, w)
}

// FindFields returns rows with selected fields from `wallet` table with arbitary where query
// whereSQL must start with "where ..."
func FindFieldsCtx[T any](ctx context.Context, whereSQL string, params ...any) ([]*T, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindCtx[T](ctx, DBName, TableName, w)
}

// Count returns select count(*) with arbitary where query
// whereSQL must start with "where ..."
func CountCtx(ctx context.Context, whereSQL string, params ...any) (int, error) {
	return coredb.QueryIntCtx(ctx, DBName, "SELECT COUNT(*) FROM `wallet` "+whereSQL, params...)
}

// FetchByPK returns a row from `wallet` table with given primary key value
func FetchByPKFromMasterCtx(ctx context.Context, val PK) (*Wallet, error) {
	return coredb.FetchByPKFromMasterCtx[Wallet](ctx, DBName, TableName, []string{"user_id", "wallet_type"}, val.UserId, val.WalletType)
}

// FetchFieldsByPK returns a row with selected fields from wallet table with given primary key value
func FetchFieldsByPKFromMasterCtx[T any](ctx context.Context, val PK) (*T, error) {
	return coredb.FetchByPKFromMasterCtx[T](ctx, DBName, TableName, []string{"user_id", "wallet_type"}, val.UserId, val.WalletType)
}

// FindOne returns a row from `wallet` table with arbitary where query
// whereSQL must start with "where ..."
func FindOneFromMasterCtx(ctx context.Context, whereSQL string, params ...any) (*Wallet, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindOneFromMasterCtx[Wallet](ctx, DBName, TableName, w)
}

// FindOneFields returns a row with selected fields from `wallet` table with arbitary where query
// whereSQL must start with "where ..."
func FindOneFieldsFromMasterCtx[T any](ctx context.Context, whereSQL string, params ...any) (*T, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindOneFromMasterCtx[T](ctx, DBName, TableName, w)
}

// Find returns rows from `wallet` table with arbitary where query
// whereSQL must start with "where ..."
func FindFromMasterCtx(ctx context.Context, whereSQL string, params ...any) ([]*Wallet, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindFromMasterCtx[Wallet](ctx, DBName, TableName, w)
}

// FindFields returns rows with selected fields from `wallet` table with arbitary where query
// whereSQL must start with "where ..."
func FindFieldsFromMasterCtx[T any](ctx context.Context, whereSQL string, params ...any) ([]*T, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindFromMasterCtx[T](ctx, DBName, TableName, w)
}

// Count returns select count(*) with arbitary where query
// whereSQL must start with "where ..."
func CountFromMasterCtx(ctx context.Context, whereSQL string, params ...any) (int, error) {
	return coredb.QueryIntFromMasterCtx(ctx, DBName, "SELECT COUNT(*) FROM `wallet` "+whereSQL, params...)
}

// Insert Wallet struct to `wallet` table
func (c *Wallet) InsertCtx(ctx context.Context) error {
	var result sql.Result
	var err error
	result, err = coredb.ExecCtx(ctx, DBName, insertWithoutPK, c.getUserIdForDB(), c.getWalletTypeForDB(), c.getWalletNameForDB(), c.getMoneyForDB())
	if err != nil {
		return err
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return err
	}
	if affectedRows == 0 {
		return coredb.ErrAvoidInsert
	}

	c.resetUpdated()
	return nil
}

// Update Wallet struct in `wallet` table
func (obj *Wallet) UpdateCtx(ctx context.Context) (bool, error) {
	var updatedFields []string
	var params []any
	if obj.WalletName.IsUpdated() {
		updatedFields = append(updatedFields, "`wallet_name` = ?")
		params = append(params, obj.getWalletNameForDB())
	}
	if obj.Money.IsUpdated() {
		updatedFields = append(updatedFields, "`money` = ?")
		params = append(params, obj.getMoneyForDB())
	}

	if len(updatedFields) == 0 {
		return false, nil
	}

	sql := "UPDATE `wallet` SET "
	sql = sql + strings.Join(updatedFields, ",") + " WHERE `user_id` = ? and `wallet_type` = ?"
	params = append(params, obj.GetUserId(), obj.GetWalletType())

	result, err := coredb.ExecCtx(ctx, DBName, sql, params...)
	if err != nil {
		return false, err
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return false, err
	}
	if affectedRows == 0 {
		return false, coredb.ErrAvoidUpdate
	}

	obj.resetUpdated()
	return true, nil
}

// Update Wallet struct with given fields in `wallet` table
func UpdateCtx(ctx context.Context, obj withPK) (bool, error) {
	var updatedFields []string
	var params []any
	var resetFuncs []func()

	val := reflect.ValueOf(obj).Elem()
	updatedFields = make([]string, 0, val.NumField())
	params = make([]any, 0, val.NumField())

	for i := 0; i < val.NumField(); i++ {
		col := val.Field(i).Addr().Interface()

		switch c := col.(type) {
		case *WalletName:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`wallet_name` = ?")
				params = append(params, c.getWalletNameForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *Money:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`money` = ?")
				params = append(params, c.getMoneyForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		}
	}

	if len(updatedFields) == 0 {
		return false, nil
	}

	sql := "UPDATE `wallet` SET "
	sql = sql + strings.Join(updatedFields, ",") + " WHERE `user_id` = ? and `wallet_type` = ?"
	params = append(params, obj.GetUserId(), obj.GetWalletType())

	result, err := coredb.ExecCtx(ctx, DBName, sql, params...)
	if err != nil {
		return false, err
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return false, err
	}
	if affectedRows == 0 {
		return false, coredb.ErrAvoidUpdate
	}

	for _, f := range resetFuncs {
		f()
	}
	return true, nil
}

// DeleteByPK delete a row from wallet table with given primary key value
func DeleteByPKCtx(ctx context.Context, val PK) error {
	_, err := coredb.ExecCtx(ctx, DBName, deleteSql, val.UserId, val.WalletType)
	return err
}
