// Code generated by gola 0.0.1; DO NOT EDIT.

package blogs

import (
	"database/sql"

	"github.com/olachat/gola/corelib"
)

var _db *sql.DB

func Setup(db *sql.DB) {
	_db = db
}

// Blog represents blogs table
type Blog struct {
	//  int
	Id
	// User Id int
	UserId
	// Slug varchar(255)
	Slug
	// Title varchar(255)
	Title
	// Category Id int
	CategoryId
	// Is pinned to top tinyint
	IsPinned
	// Is VIP reader only tinyint
	IsVip
	// Country of the blog user varchar(255)
	Country
	// Created Timestamp int unsigned
	CreatedAt
	// Updated Timestamp int unsigned
	UpdatedAt
}

type BlogTable struct{}

func (*BlogTable) GetTableName() string {
	return "blogs"
}

var table *BlogTable

// Fetch methods
func FetchBlogById(id int) *Blog {
	return corelib.FetchById[Blog](id, _db)
}

func FetchById[T any](id int) *T {
	return corelib.FetchById[T](id, _db)
}

func FetchBlogByIds(ids []int) []*Blog {
	return corelib.FetchByIds[Blog](ids, _db)
}

func FetchByIds[T any](ids []int) []*T {
	return corelib.FetchByIds[T](ids, _db)
}

// Column types

// Id field
//
type Id struct {
	val int
}

func (c *Id) GetId() int {
	return c.val
}

func (c *Id) SetId(val int) {
	c.val = val
}

func (c *Id) GetColumnName() string {
	return "id"
}

func (c *Id) IsPrimaryKey() bool {
	return true
}

func (c *Id) GetValPointer() interface{} {
	return &c.val
}

func (c *Id) GetTableType() corelib.TableType {
	return table
}

// UserId field
// User Id
type UserId struct {
	val int
}

func (c *UserId) GetUserId() int {
	return c.val
}

func (c *UserId) SetUserId(val int) {
	c.val = val
}

func (c *UserId) GetColumnName() string {
	return "user_id"
}

func (c *UserId) IsPrimaryKey() bool {
	return false
}

func (c *UserId) GetValPointer() interface{} {
	return &c.val
}

func (c *UserId) GetTableType() corelib.TableType {
	return table
}

// Slug field
// Slug
type Slug struct {
	val string
}

func (c *Slug) GetSlug() string {
	return c.val
}

func (c *Slug) SetSlug(val string) {
	c.val = val
}

func (c *Slug) GetColumnName() string {
	return "slug"
}

func (c *Slug) IsPrimaryKey() bool {
	return false
}

func (c *Slug) GetValPointer() interface{} {
	return &c.val
}

func (c *Slug) GetTableType() corelib.TableType {
	return table
}

// Title field
// Title
type Title struct {
	val string
}

func (c *Title) GetTitle() string {
	return c.val
}

func (c *Title) SetTitle(val string) {
	c.val = val
}

func (c *Title) GetColumnName() string {
	return "title"
}

func (c *Title) IsPrimaryKey() bool {
	return false
}

func (c *Title) GetValPointer() interface{} {
	return &c.val
}

func (c *Title) GetTableType() corelib.TableType {
	return table
}

// CategoryId field
// Category Id
type CategoryId struct {
	val int
}

func (c *CategoryId) GetCategoryId() int {
	return c.val
}

func (c *CategoryId) SetCategoryId(val int) {
	c.val = val
}

func (c *CategoryId) GetColumnName() string {
	return "category_id"
}

func (c *CategoryId) IsPrimaryKey() bool {
	return false
}

func (c *CategoryId) GetValPointer() interface{} {
	return &c.val
}

func (c *CategoryId) GetTableType() corelib.TableType {
	return table
}

// IsPinned field
// Is pinned to top
type IsPinned struct {
	val int8
}

func (c *IsPinned) GetIsPinned() int8 {
	return c.val
}

func (c *IsPinned) SetIsPinned(val int8) {
	c.val = val
}

func (c *IsPinned) GetColumnName() string {
	return "is_pinned"
}

func (c *IsPinned) IsPrimaryKey() bool {
	return false
}

func (c *IsPinned) GetValPointer() interface{} {
	return &c.val
}

func (c *IsPinned) GetTableType() corelib.TableType {
	return table
}

// IsVip field
// Is VIP reader only
type IsVip struct {
	val int8
}

func (c *IsVip) GetIsVip() int8 {
	return c.val
}

func (c *IsVip) SetIsVip(val int8) {
	c.val = val
}

func (c *IsVip) GetColumnName() string {
	return "is_vip"
}

func (c *IsVip) IsPrimaryKey() bool {
	return false
}

func (c *IsVip) GetValPointer() interface{} {
	return &c.val
}

func (c *IsVip) GetTableType() corelib.TableType {
	return table
}

// Country field
// Country of the blog user
type Country struct {
	val string
}

func (c *Country) GetCountry() string {
	return c.val
}

func (c *Country) SetCountry(val string) {
	c.val = val
}

func (c *Country) GetColumnName() string {
	return "country"
}

func (c *Country) IsPrimaryKey() bool {
	return false
}

func (c *Country) GetValPointer() interface{} {
	return &c.val
}

func (c *Country) GetTableType() corelib.TableType {
	return table
}

// CreatedAt field
// Created Timestamp
type CreatedAt struct {
	val uint
}

func (c *CreatedAt) GetCreatedAt() uint {
	return c.val
}

func (c *CreatedAt) SetCreatedAt(val uint) {
	c.val = val
}

func (c *CreatedAt) GetColumnName() string {
	return "created_at"
}

func (c *CreatedAt) IsPrimaryKey() bool {
	return false
}

func (c *CreatedAt) GetValPointer() interface{} {
	return &c.val
}

func (c *CreatedAt) GetTableType() corelib.TableType {
	return table
}

// UpdatedAt field
// Updated Timestamp
type UpdatedAt struct {
	val uint
}

func (c *UpdatedAt) GetUpdatedAt() uint {
	return c.val
}

func (c *UpdatedAt) SetUpdatedAt(val uint) {
	c.val = val
}

func (c *UpdatedAt) GetColumnName() string {
	return "updated_at"
}

func (c *UpdatedAt) IsPrimaryKey() bool {
	return false
}

func (c *UpdatedAt) GetValPointer() interface{} {
	return &c.val
}

func (c *UpdatedAt) GetTableType() corelib.TableType {
	return table
}

func NewBlog() *Blog {
	return &Blog{
		Id{},
		UserId{val: int(0)},
		Slug{val: ""},
		Title{val: ""},
		CategoryId{val: int(0)},
		IsPinned{val: int8(0)},
		IsVip{val: int8(0)},
		Country{val: ""},
		CreatedAt{val: uint(0)},
		UpdatedAt{val: uint(0)},
	}
}

func (c *Blog) Insert() error {
	sql := `INSERT INTO blogs (user_id, slug, title, category_id, is_pinned, is_vip, country, created_at, updated_at) values (?, ?, ?, ?, ?, ?, ?, ?, ?)`

	result, err := corelib.Exec[Blog](sql, _db, c.GetUserId(), c.GetSlug(), c.GetTitle(), c.GetCategoryId(), c.GetIsPinned(), c.GetIsVip(), c.GetCountry(), c.GetCreatedAt(), c.GetUpdatedAt())

	if err != nil {
		return err
	}
	id, err := result.LastInsertId()
	if err != nil {
		return err
	}

	c.SetId(int(id))
	return nil
}
