// Code generated by gola 0.1.1; DO NOT EDIT.

package xs_pay_change_new

import (
	"context"
	"database/sql"
	"reflect"
	"strings"

	"github.com/olachat/gola/v2/coredb"
)

// FetchByPK returns a row from `xs_pay_change_new` table with given primary key value
func FetchByPKCtx(ctx context.Context, val PK) (*XsPayChangeNew, error) {
	return coredb.FetchByPKCtx[XsPayChangeNew](ctx, DBName, TableName, []string{"id", "dateline"}, val.Id, val.Dateline)
}

// FetchFieldsByPK returns a row with selected fields from xs_pay_change_new table with given primary key value
func FetchFieldsByPKCtx[T any](ctx context.Context, val PK) (*T, error) {
	return coredb.FetchByPKCtx[T](ctx, DBName, TableName, []string{"id", "dateline"}, val.Id, val.Dateline)
}

// FindOne returns a row from `xs_pay_change_new` table with arbitary where query
// whereSQL must start with "where ..."
func FindOneCtx(ctx context.Context, whereSQL string, params ...any) (*XsPayChangeNew, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindOneCtx[XsPayChangeNew](ctx, DBName, TableName, w)
}

// FindOneFields returns a row with selected fields from `xs_pay_change_new` table with arbitary where query
// whereSQL must start with "where ..."
func FindOneFieldsCtx[T any](ctx context.Context, whereSQL string, params ...any) (*T, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindOneCtx[T](ctx, DBName, TableName, w)
}

// Find returns rows from `xs_pay_change_new` table with arbitary where query
// whereSQL must start with "where ..."
func FindCtx(ctx context.Context, whereSQL string, params ...any) ([]*XsPayChangeNew, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindCtx[XsPayChangeNew](ctx, DBName, TableName, w)
}

// FindFields returns rows with selected fields from `xs_pay_change_new` table with arbitary where query
// whereSQL must start with "where ..."
func FindFieldsCtx[T any](ctx context.Context, whereSQL string, params ...any) ([]*T, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindCtx[T](ctx, DBName, TableName, w)
}

// Count returns select count(*) with arbitary where query
// whereSQL must start with "where ..."
func CountCtx(ctx context.Context, whereSQL string, params ...any) (int, error) {
	return coredb.QueryIntCtx(ctx, DBName, "SELECT COUNT(*) FROM `xs_pay_change_new` "+whereSQL, params...)
}

// FetchByPK returns a row from `xs_pay_change_new` table with given primary key value
func FetchByPKFromMasterCtx(ctx context.Context, val PK) (*XsPayChangeNew, error) {
	return coredb.FetchByPKFromMasterCtx[XsPayChangeNew](ctx, DBName, TableName, []string{"id", "dateline"}, val.Id, val.Dateline)
}

// FetchFieldsByPK returns a row with selected fields from xs_pay_change_new table with given primary key value
func FetchFieldsByPKFromMasterCtx[T any](ctx context.Context, val PK) (*T, error) {
	return coredb.FetchByPKFromMasterCtx[T](ctx, DBName, TableName, []string{"id", "dateline"}, val.Id, val.Dateline)
}

// FindOne returns a row from `xs_pay_change_new` table with arbitary where query
// whereSQL must start with "where ..."
func FindOneFromMasterCtx(ctx context.Context, whereSQL string, params ...any) (*XsPayChangeNew, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindOneFromMasterCtx[XsPayChangeNew](ctx, DBName, TableName, w)
}

// FindOneFields returns a row with selected fields from `xs_pay_change_new` table with arbitary where query
// whereSQL must start with "where ..."
func FindOneFieldsFromMasterCtx[T any](ctx context.Context, whereSQL string, params ...any) (*T, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindOneFromMasterCtx[T](ctx, DBName, TableName, w)
}

// Find returns rows from `xs_pay_change_new` table with arbitary where query
// whereSQL must start with "where ..."
func FindFromMasterCtx(ctx context.Context, whereSQL string, params ...any) ([]*XsPayChangeNew, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindFromMasterCtx[XsPayChangeNew](ctx, DBName, TableName, w)
}

// FindFields returns rows with selected fields from `xs_pay_change_new` table with arbitary where query
// whereSQL must start with "where ..."
func FindFieldsFromMasterCtx[T any](ctx context.Context, whereSQL string, params ...any) ([]*T, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindFromMasterCtx[T](ctx, DBName, TableName, w)
}

// Count returns select count(*) with arbitary where query
// whereSQL must start with "where ..."
func CountFromMasterCtx(ctx context.Context, whereSQL string, params ...any) (int, error) {
	return coredb.QueryIntFromMasterCtx(ctx, DBName, "SELECT COUNT(*) FROM `xs_pay_change_new` "+whereSQL, params...)
}

// Insert XsPayChangeNew struct to `xs_pay_change_new` table
func (c *XsPayChangeNew) InsertCtx(ctx context.Context) error {
	var result sql.Result
	var err error
	result, err = coredb.ExecCtx(ctx, DBName, insertWithoutPK, c.getUidForDB(), c.getDatelineForDB(), c.getMoneyForDB(), c.getOpForDB(), c.getReasonForDB(), c.getSubjectForDB(), c.getDeletedForDB())
	if err != nil {
		return err
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return err
	}
	if affectedRows == 0 {
		return coredb.ErrAvoidInsert
	}

	c.resetUpdated()
	return nil
}

// Update XsPayChangeNew struct in `xs_pay_change_new` table
func (obj *XsPayChangeNew) UpdateCtx(ctx context.Context) (bool, error) {
	var updatedFields []string
	var params []any
	if obj.Uid.IsUpdated() {
		updatedFields = append(updatedFields, "`uid` = ?")
		params = append(params, obj.getUidForDB())
	}
	if obj.Money.IsUpdated() {
		updatedFields = append(updatedFields, "`money` = ?")
		params = append(params, obj.getMoneyForDB())
	}
	if obj.Op.IsUpdated() {
		updatedFields = append(updatedFields, "`op` = ?")
		params = append(params, obj.getOpForDB())
	}
	if obj.Reason.IsUpdated() {
		updatedFields = append(updatedFields, "`reason` = ?")
		params = append(params, obj.getReasonForDB())
	}
	if obj.Subject.IsUpdated() {
		updatedFields = append(updatedFields, "`subject` = ?")
		params = append(params, obj.getSubjectForDB())
	}
	if obj.Deleted.IsUpdated() {
		updatedFields = append(updatedFields, "`deleted` = ?")
		params = append(params, obj.getDeletedForDB())
	}

	if len(updatedFields) == 0 {
		return false, nil
	}

	sql := "UPDATE `xs_pay_change_new` SET "
	sql = sql + strings.Join(updatedFields, ",") + " WHERE `id` = ? and `dateline` = ?"
	params = append(params, obj.GetId(), obj.GetDateline())

	result, err := coredb.ExecCtx(ctx, DBName, sql, params...)
	if err != nil {
		return false, err
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return false, err
	}
	if affectedRows == 0 {
		return false, coredb.ErrAvoidUpdate
	}

	obj.resetUpdated()
	return true, nil
}

// Update XsPayChangeNew struct with given fields in `xs_pay_change_new` table
func UpdateCtx(ctx context.Context, obj withPK) (bool, error) {
	var updatedFields []string
	var params []any
	var resetFuncs []func()

	val := reflect.ValueOf(obj).Elem()
	updatedFields = make([]string, 0, val.NumField())
	params = make([]any, 0, val.NumField())

	for i := 0; i < val.NumField(); i++ {
		col := val.Field(i).Addr().Interface()

		switch c := col.(type) {
		case *Uid:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`uid` = ?")
				params = append(params, c.getUidForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *Money:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`money` = ?")
				params = append(params, c.getMoneyForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *Op:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`op` = ?")
				params = append(params, c.getOpForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *Reason:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`reason` = ?")
				params = append(params, c.getReasonForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *Subject:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`subject` = ?")
				params = append(params, c.getSubjectForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *Deleted:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`deleted` = ?")
				params = append(params, c.getDeletedForDB())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		}
	}

	if len(updatedFields) == 0 {
		return false, nil
	}

	sql := "UPDATE `xs_pay_change_new` SET "
	sql = sql + strings.Join(updatedFields, ",") + " WHERE `id` = ? and `dateline` = ?"
	params = append(params, obj.GetId(), obj.GetDateline())

	result, err := coredb.ExecCtx(ctx, DBName, sql, params...)
	if err != nil {
		return false, err
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return false, err
	}
	if affectedRows == 0 {
		return false, coredb.ErrAvoidUpdate
	}

	for _, f := range resetFuncs {
		f()
	}
	return true, nil
}

// DeleteByPK delete a row from xs_pay_change_new table with given primary key value
func DeleteByPKCtx(ctx context.Context, val PK) error {
	_, err := coredb.ExecCtx(ctx, DBName, deleteSql, val.Id, val.Dateline)
	return err
}
